@echo off
echo Starting No Limits 2...
start "" "C:\Program Files (x86)\Steam\steamapps\common\NoLimits 2\64bit\nolimits2stm.exe"

echo Starting Python script...
python "C:\Users\Drexel\Desktop\sb4249.github.io-2way\wrapper.py"